Parse events from Google Calendar
waterloo-rocketry/minerva-rewrite pull request #57
Opened 2023-12-23 05:39 UTC by wxp02

## Description
This PR introduces two new utility functions for retrieving and parsing Google Calendar events into a custom `CalendarEvent` class. The goal is to provide a convenient way to fetch upcoming events within the next 24 hours and filter events by a specific Slack channel.

1. Added a new function `parseEvents`:
    - Parses all events from all channels in the next 24 hours into a list of `CalendarEvent` instances.

2. Added a new function `parseEventsByChannel`:
    - Takes a `channelNames` as an argument and filters upcoming events for that specific channel.

## Developer Testing
Tested script locally

## Reviewer Testing

2023-12-23 13:10 UTC, Darth-Raazi approved these changes
2 small comments, but <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-:-NmLmzmM1VS5b3l1gfCf:b-1dopup)* status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/index.ts` line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmLmES71L8nIMupuce1:-NmLmES71L8nIMupuce2:b-mb50ul) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/231b15ab21424a208ccc1490f18bc915b20b779a/src/index.ts#L27)):*
> ```XML
>     clientId: process.env.GOOGLE_ACCOUNT_CLIENT,
>     clientSecret: process.env.GOOGLE_ACCOUNT_SECRET,
>     redirectUri: "https://developers.google.com/oauthplayground",
> ```

Should this link be in some sort of global/environment variable?
___
*[`src/index.ts` line 84 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmLml7RBDG3oQpyTkSM:-NmLmZP_BO0r_0iE-ZG2:bheh6xd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/231b15ab21424a208ccc1490f18bc915b20b779a/src/index.ts#L84)):*
> ```XML
>   };
> 
>   while (true) {}
> ```

I'm assuming this is a placeholder until we add more functionality?


<!-- Sent from Reviewable.io -->

2023-12-23 16:21 UTC, QuantumManiac requested changes
Looks good so far! For the next step, can we move all this functionality into its own dedicated file? Perhaps something like `src/utils/googleCalendar` or something.

I'll hold up on a more in-depth review until that's taken care of. It would also be good to write up something quick to expose the functionality through the Dev Slackbot so reviewers can verify its functionality. E.g. a slash command or a message event handler that responds with a message containing upcoming calendar events and their info. It doesn't have to be pretty, you could just dump the JSON response into a message if you want.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-:-NmMT1HP2v7kkst8dCTV:b-656k9f)* status: all files reviewed, 3 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/index.ts` line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmMSZfu09jvUGe48qSN:-NmMSZfu09jvUGe48qSO:bmhab95) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/231b15ab21424a208ccc1490f18bc915b20b779a/src/index.ts#L21)):*
> ```XML
> registerListeners(app);
> 
> // Setup Google OAuth
> ```

Could we have the Google OAuth initialization before the Slack app initialization? This is usually the more common initialization to fail, so it would be good to have it fail early.
___
*[`src/index.ts` line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmLmES71L8nIMupuce1:-NmMSPZC0hk6lqcfCd-Q:byx0psf) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/231b15ab21424a208ccc1490f18bc915b20b779a/src/index.ts#L27)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Should this link be in some sort of global/environment variable?
</blockquote></details>

Yes, please change to `process.env.GOOGLE_ACCOUNT_OAUTH_REDIRECT`
___
*[`src/index.ts` line 84 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmLml7RBDG3oQpyTkSM:-NmMSq4qDr0wqKC4mXMt:bdudpkg) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/231b15ab21424a208ccc1490f18bc915b20b779a/src/index.ts#L84)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

I'm assuming this is a placeholder until we add more functionality?
</blockquote></details>

Correct. If we let the script exit it gets stuck in a crash loop.


<!-- Sent from Reviewable.io -->

2023-12-24 01:06 UTC, wxp02 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/index.ts` line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmMSZfu09jvUGe48qSN:-NmNL3875rqsapyrZsor:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/231b15ab21424a208ccc1490f18bc915b20b779a/src/index.ts#L21)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Could we have the Google OAuth initialization before the Slack app initialization? This is usually the more common initialization to fail, so it would be good to have it fail early.
</blockquote></details>

Done.
___
*[`src/index.ts` line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmLmES71L8nIMupuce1:-NmNHGuW0FjyD-5-n1zg:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/231b15ab21424a208ccc1490f18bc915b20b779a/src/index.ts#L27)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Yes, please change to `process.env.GOOGLE_ACCOUNT_OAUTH_REDIRECT`
</blockquote></details>

Done.
___
*[`src/index.ts` line 84 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmLml7RBDG3oQpyTkSM:-NmNHSVWDUhBdC6s30-z:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/231b15ab21424a208ccc1490f18bc915b20b779a/src/index.ts#L84)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Correct. If we let the script exit it gets stuck in a crash loop.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-24 01:07 UTC, wxp02 commented
Moved all functions into `src/utils/googleCalendar`. Will now work on exposing the functionality through the Dev Slackbot so reviewers can verify its functionality.





<!-- Sent from Reviewable.io -->

2023-12-25 18:56 UTC, wxp02 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/utils/googleCalendar.ts` line 9 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmSNytA9SI1fLnV9l9Y:-NmXGJto-djkRONR7zxO:b-wv3qqb) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/e6bc8b48efa0eed287a5db2ae444850cce2d8e00/src/utils/googleCalendar.ts#L9)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

What are your thoughts on having the google client initialization (`const auth = ...`) in `index.ts` and passing it into the functions that you have in this file as a parameter? I think either way is fine for the most part, I'm just not sure which way would be easier to work with. Maybe the suggestion above in case we end up using the google client for more than just Google Calendar?
</blockquote></details>

I think is a good idea, fixed this
___
*[`src/utils/googleCalendar.ts` line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmSPSoK-Q4h8CbSABgt:-NmXEzKmBtP0YN9IdHTL:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/e6bc8b48efa0eed287a5db2ae444850cce2d8e00/src/utils/googleCalendar.ts#L22)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Could you populate the functions in this file with JSDocs? See [here](https://stackoverflow.com/questions/34220564/is-there-a-way-to-generate-jsdoc-comments-in-visual-studio-code) for how to generate the template easily, and my code under `utils/` for some examples of already-written JSDocs

Additionally, please explicitly specify the return type of the function
</blockquote></details>

Done.
___
*[`src/utils/googleCalendar.ts` line 39 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmSQ9eC47UIkeqc37Kz:-NmXDMRz4V7LDynaFaR5:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/e6bc8b48efa0eed287a5db2ae444850cce2d8e00/src/utils/googleCalendar.ts#L39)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Can you explicitly specify a return type for this? I think it's probably `Promise<CalendarEvent[]>`?
</blockquote></details>

Done.
___
*[`src/utils/googleCalendar.ts` line 47 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmSQIFzBSQZUd19Rdqc:-NmXDIrP8_MwjqypV_c4:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/e6bc8b48efa0eed287a5db2ae444850cce2d8e00/src/utils/googleCalendar.ts#L47)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Could we just return an empty array instead? It doesn't make too much sense to return an array of events or a string
</blockquote></details>

Done.
___
*[`src/utils/googleCalendar.ts` line 53 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmSR9sQ-AWmKG_QwPKV:-NmXDJa14vl7i6rgeIjz:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/e6bc8b48efa0eed287a5db2ae444850cce2d8e00/src/utils/googleCalendar.ts#L53)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Same as previous comments, please explicitly specify a return type
</blockquote></details>

Done.
___
*[`src/utils/googleCalendar.ts` line 66 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmSREU_68WTBLxdlO1k:-NmXCutN8fIObp6zxEiW:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/e6bc8b48efa0eed287a5db2ae444850cce2d8e00/src/utils/googleCalendar.ts#L66)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Same as above, probably better to just return an empty array
</blockquote></details>

Done.
___
*[`src/classes/CalendarEvent.ts` line 42 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmSNl1l1XVhYS151juo:-NmXC_Z3AgzuN0bdIZOI:bcjkzns) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/e6bc8b48efa0eed287a5db2ae444850cce2d8e00/src/classes/CalendarEvent.ts#L42)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Are the `?` necessary? I think it would be safe enough to assume that `dateTime` exists if `start` and `end` exist.
</blockquote></details>

Removed the ? for these 2 lines



_Code snippet:_
```XML
this.start = new Date(event.start.dateTime);
this.end = new Date(event.end.dateTime);
```


<!-- Sent from Reviewable.io -->

2023-12-26 00:01 UTC, wxp02 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/index.ts` line 29 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmXiyrMD4apm1u3BKpE:-NmYQFw-CRZ_kUqmi00v:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/796f2c05220a56ed551d7e59ba4eecfc43bf6816/src/index.ts#L29)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Ah, sorry, missed this too - instead of having all the Google auth initialization in the `main()` function, could you just put it (and everything else that needs to be executed async) into the IIFE, the
```
(async (): Promise<void> => {
  ...
})();
```
and get rid of the `main()` function entirely? You can probably move `registerListeners(app);` above the IIFE but below the slack app initialization as it doesn't need to be executed async.

Alternatively, you could move everything in the IIFE into the `main()` function, get rid of the IIFE, and then just call main() as we currently are. Both are fine so whichever you prefer. The point is that we don't want both at the same time as the IIFE is essentially acting as the main function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-26 15:15 UTC, QuantumManiac requested changes
One more fix and then you should be good to go! Any progress on implementing functionality that allows for reviewers to test this?

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-:-NmagGJs6JWQmkqCam_r:b8pc5az)* status: all files reviewed, 3 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/utils/googleCalendar.ts` line 57 at r4](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmaevp49OZdGIgegatd:-Nmaevp49OZdGIgegate:buis82h) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/452c1efcb12ed51491d953cf1db44b4873f581d7/src/utils/googleCalendar.ts#L57)):*
> ```XML
>  * @returns A promise that resolves to the list of parsed CalendarEvents.
>  */
> export async function parseEventsOfChannels(
> ```

Instead of having two different functions that parse the `calendar_v3.Schema$Events` fetched from the Google Calendar API in their own way, it might be better to just pass in an array of `CalendarEvent` (presumably the result of  `parseEvents`) and then just filter that. It's good to avoid passing around the non-parsed results of an API response between your functions, i.e. instead of passing around `calendar_v3.Schema$Events`, parse it into `CalendarEvent`s instead so all the functions that take care of that data don't have to parse it themselves.   


<!-- Sent from Reviewable.io -->

2023-12-26 16:27 UTC, QuantumManiac requested changes
Noticed one more thing as I was looking through the code.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-:-Nmawr45AUV4GVLH46M4:b-xhs5ug)* status: all files reviewed, 4 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/index.ts` line 4 at r4](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmaw-IvB2-7jUv6WVRF:-Nmaw-IvB2-7jUv6WVRG:b-fzbnk8) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/452c1efcb12ed51491d953cf1db44b4873f581d7/src/index.ts#L4)):*
> ```XML
> import * as environment from "./utils/env";
> import registerListeners from "./listeners";
> import { OAuth2Client } from "google-auth-library";
> ```

We could probably make use of `googleapis` instead of `google-auth-library` for this since we're using the former already and OAuth stuff comes built-in.



_Suggestion (i):_
```XML
import { google } from "googleapis";
```



_Suggestion (ii):_
```XML
const auth = new google.auth.OAuth2({
```


<!-- Sent from Reviewable.io -->

2023-12-26 16:30 UTC, QuantumManiac reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57)* status: all files reviewed, 3 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/index.ts` line 4 at r4](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmaw-IvB2-7jUv6WVRF:-NmaxcJD5t2FAynIaWCS:boa871) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/452c1efcb12ed51491d953cf1db44b4873f581d7/src/index.ts#L4)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

We could probably make use of `googleapis` instead of `google-auth-library` for this since we're using the former already and OAuth stuff comes built-in.
</blockquote></details>

Nevermind, I did a bit more digging and it seems that ``google-auth-library`just comes bundled in with `googleapis`


<!-- Sent from Reviewable.io -->

2023-12-26 23:14 UTC, wxp02 commented
*[`src/utils/googleCalendar.ts` line 57 at r4](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmaevp49OZdGIgegatd:-NmcP6rb4ighf5j1xOXb:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/452c1efcb12ed51491d953cf1db44b4873f581d7/src/utils/googleCalendar.ts#L57)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Instead of having two different functions that parse the `calendar_v3.Schema$Events` fetched from the Google Calendar API in their own way, it might be better to just pass in an array of `CalendarEvent` (presumably the result of  `parseEvents`) and then just filter that. It's good to avoid passing around the non-parsed results of an API response between your functions, i.e. instead of passing around `calendar_v3.Schema$Events`, parse it into `CalendarEvent`s instead so all the functions that take care of that data don't have to parse it themselves.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-26 23:16 UTC, wxp02 commented
Made all the necessary changes. Added the testing process and cases in the main PR page https://github.com/waterloo-rocketry/minerva-rewrite/pull/57





<!-- Sent from Reviewable.io -->

2023-12-28 14:04 UTC, QuantumManiac requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> Dismissed @Darth-Raazi from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57)* status: all files reviewed, 3 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/utils/googleCalendar.ts` line 28 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmkhAyMBT0Sr_iClq19:-NmkhAyMBT0Sr_iClq1A:b-fju4b9) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/utils/googleCalendar.ts#L28)):*
> ```XML
> 
> /**
>  * Parses events from all channels in the next 24 hours into a list of CalendarEvents.
> ```

This, along with the `nextEvents` parameter, should probably be more generic because the user could pass in any array of calendar events from the Google API
 



_Suggestion (i):_
```XML
 * Parses events fetched from the Google API into a list of CalendarEvents.
```



_Suggestion (ii):_
```XML
  events: calendar_v3.Schema$Events,
```
___
*[`src/utils/googleCalendar.ts` line 50 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmkhuqs78qKxDHjpO3K:-Nmkhuqs78qKxDHjpO3L:b-w6scj6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/utils/googleCalendar.ts#L50)):*
> ```XML
> 
> /**
>  * Parses events from specified Slack channels in the next 24 hours into a list of CalendarEvents.
> ```

Same comment as above re: a more generic function for this



_Suggestion:_
```XML
 * Filters CalendarEvents into those only from specified Slack channels.
```
___
*[`src/utils/googleCalendar.ts` line 60 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmkiMmd3dApPUT8aKPh:-NmkiMmd3dApPUT8aKPi:b-g260qx) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/utils/googleCalendar.ts#L60)):*
> ```XML
> ): Promise<CalendarEvent[]> {
>   const filteredEvents = calendarEvents.filter((event) =>
>     channelNames.includes(event.minervaEventMetadata?.channel?.name ?? ""),
> ```

Since `channel` is a required field for `minervaEventMetadata` (or at least should be) and `name` is a required field for `SlackChannel`, it might be cleaner to check if `minervaEventMetadata` exists rather than if `minervaEventMetadata.channel.name` exists.

On this topic, would you mind changing the `channel` field in `EventMetadata` under `/src/utils/calendarDescription.ts` to be non-optional? On Line 13, remove the `?` in front of `channel`.


<!-- Sent from Reviewable.io -->

2023-12-28 15:00 UTC, QuantumManiac requested changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57)* status: all files reviewed, 5 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/index.ts` line 8 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmkw1fwArs2KN3mqlla:-Nmkw1fwArs2KN3mqllb:b6yfilz) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/index.ts#L8)):*
> ```XML
> // Set up Google OAuth2 client
> const auth = new OAuth2Client({
>   clientId: process.env.GOOGLE_ACCOUNT_CLIENT,
> ```

Sorry for the misinformation, you should be using `env.ts` for this instead



_Suggestion (i):_
```XML
  clientId: environment.googleAccountClient,
  clientSecret: environment.googleAccountSecret,
  redirectUri: environment.googleAccountOauthRedirect,
  
```



_Suggestion (ii):_
```XML
  refresh_token: environment.googleAccountToken,
```


<!-- Sent from Reviewable.io -->

2023-12-28 18:15 UTC, wxp02 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/index.ts` line 8 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmkw1fwArs2KN3mqlla:-NmlYpOG31F6vbkDUhK6:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/index.ts#L8)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Sorry for the misinformation, you should be using `env.ts` for this instead
</blockquote></details>

Done.
___
*[`src/utils/googleCalendar.ts` line 28 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmkhAyMBT0Sr_iClq19:-Nml_kmyApDOdpLKz-j3:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/utils/googleCalendar.ts#L28)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

This, along with the `nextEvents` parameter, should probably be more generic because the user could pass in any array of calendar events from the Google API
</blockquote></details>

Done.
___
*[`src/utils/googleCalendar.ts` line 50 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmkhuqs78qKxDHjpO3K:-Nmla-J3-Qk3ZVGEg262:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/utils/googleCalendar.ts#L50)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Same comment as above re: a more generic function for this
</blockquote></details>

Done.
___
*[`src/utils/googleCalendar.ts` line 58 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmko25u4enR76iJc5Dw:-NmlaFCg8U9dc0HSrG7W:btwvj28) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/utils/googleCalendar.ts#L58)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Since it's just filtering, does the function need to be async and return a promise?
</blockquote></details>

Yea good catch, it doesn't need to be async and return a promise. Changed this
___
*[`src/utils/googleCalendar.ts` line 60 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-NmkiMmd3dApPUT8aKPh:-Nmlcn_J2xQAESq6r72I:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/1cf489d0fbc829a6d98c98065994c0e53700a014/src/utils/googleCalendar.ts#L60)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Since `channel` is a required field for `minervaEventMetadata` (or at least should be) and `name` is a required field for `SlackChannel`, it might be cleaner to check if `minervaEventMetadata` exists rather than if `minervaEventMetadata.channel.name` exists.

On this topic, would you mind changing the `channel` field in `EventMetadata` under `/src/utils/calendarDescription.ts` to be non-optional? On Line 13, remove the `?` in front of `channel`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-28 20:44 UTC, QuantumManiac approved these changes
I think we're finally good to go! 
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-:-Nmm9pvV7V8NOgf7wqXA:b-s9lov0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/utils/calendarDescription.ts` line 13 at r6](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/57#-Nmm8zV336UaBNhujxt7:-Nmm8zV336UaBNhujxt8:b-ucfknh) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/60b9f6aecb51046110526dc939ec82dedea30304/src/utils/calendarDescription.ts#L13)):*
> ```XML
>    * The channel that event reminders should be posted to
>    */
>   channel?: SlackChannel;
> ```

Thanks!


<!-- Sent from Reviewable.io -->

2023-12-28 20:49 UTC, merged