Single channel guests function
waterloo-rocketry/minerva-rewrite pull request #60
Opened 2023-12-31 05:38 UTC by wxp02

## Description

- [ ] Implement functionality to get all single-channel guests in the slack workspace
  - [ ] Ensure that the function to get all users in a slack workspace supports pagination
  - [ ] Create a new class in the project to parse the JSON response into something more easily usable by the application, with only necessary data (e.g. user's name, ID, and role should be sufficient for now)
- [ ]  Implement functionality to get all single-channel guests in a specified channel
- [ ]  Implement functionality to send a DM to all single-channel guests in a specified channel

This PR closes #20.

## Developer Testing

## Reviewer Testing

2024-01-01 22:02 UTC, wxp02 commented
*[`src/utils/guests.ts` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn61uT_AprorXiO4Dih:-Nn61uT_AprorXiO4Dii:b-9agv42) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L22)):*
> ```XML
>       users.members.forEach((user) => {
>         if (user.is_ultra_restricted) {
>           const newGuest = new SlackGuest(user.real_name as string, user.id as string, user.team_id as string);
> ```

I'm not too sure what is the role parameter in the users.list API so I just put team_id for now



_Code quote:_
```XML
user.team_id
```


<!-- Sent from Reviewable.io -->

2024-01-01 22:33 UTC, QuantumManiac requested changes
Looks good so far! Left a few comments.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-:-Nn69BfpE6f7pPhJFaq9:bhy7s8u)* status: all files reviewed, 8 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/classes/SlackGuest.ts` line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn65YSY2CFPTUn9Wh9X:-Nn65YSY2CFPTUn9Wh9Y:b-k5sap2) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/classes/SlackGuest.ts#L4)):*
> ```XML
>  * Class representing a slack guest
>  */
> export default class SlackGuest {
> ```

Could we generalize this into something like a `SlackUser` class? We can rename the `role` field into something like `userType` and use it to specify what kind of user they are, e.g. admin, owner, restricted (multi-channel guest), ultra_restricted (single-channel guest).

For `userType`, I would suggest that you use something like an enum to define them. 
___
*[`src/utils/guests.ts` line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn67XtNAObH4N90Nqil:-Nn67XtNAObH4N90Nqim:b-exgdzs) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L14)):*
> ```XML
> 
>   do {
>     const users = await app.client.users.list({
> ```

You should move out the `app.client.users.list` call and parsing the reponse into a list of `SlackUser`s into its own function under `src/utils/slack.ts`. Having it as its own function would make it easier to stub it out for unit testing purposes. 

Also note that this function fetches both active and deactivated users. We can definitely ignore deactivated users so your function could probably filter them out.
___
*[`src/utils/guests.ts` line 15 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn66jMG7XMfcixZsOq5:-Nn66jMG7XMfcixZsOq6:b93fdmw) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L15)):*
> ```XML
>   do {
>     const users = await app.client.users.list({
>       limit: 200,
> ```

After some testing on the old minerva, we found out that the limit can be as high as 1000, so we could change this to something like 900 to ensure that we don't need to do pagination unless absolutely needed? Even now, there are 315 active accounts on the slack.
___
*[`src/utils/guests.ts` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn61uT_AprorXiO4Dih:-Nn66YDc5fj9GI_-nRZI:bsjqoyh) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L22)):*
<details><summary><i>Previously, wxp02 (Wenxu Poh) wrote…</i></summary><blockquote>

I'm not too sure what is the role parameter in the users.list API so I just put team_id for now
</blockquote></details>

Sorry, I didn't recall what Slack actually called this. By role, I mean user type as per my previous comment. 
___
*[`src/utils/guests.ts` line 36 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68hCmDtpjI_on_xCX:-Nn68hCmDtpjI_on_xCY:b-yv4efy) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L36)):*
> ```XML
> /**
>  * Retrieves a list of SlackGuests of single channel guests in a specific channel.
>  * @param app The Slack Bolt app instance.
> ```

This JSDoc seems to be missing some parameters e.g. `channel` 
___
*[`src/utils/guests.ts` line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68Ha721VrznSaaAIf:-Nn68Ha721VrznSaaAIg:b5amhsd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L41)):*
> ```XML
> export async function getAllSingleChannelGuestsInChannel(
>   app: App,
>   channel: string,
> ```

It would be preferable to pass in a `SlackChannel` instead. Additionally, it would be good to either make it such that this function can be passed multiple channels to get all the single channel guests from or create a new getAllSingleChannelGuestsInChannel**s** function to do that
___
*[`src/utils/guests.ts` line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68w-O3ShzPJwRBuFx:-Nn68w-O3ShzPJwRBuFy:b7h6p2h) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L44)):*
> ```XML
>   singleChannelGuests: SlackGuest[],
> ): Promise<SlackGuest[]> {
>   const guestMembersInChannel = await app.client.conversations.members({
> ```

You should move this into its own function, similar to my suggestion for `app.client.users.list`. Additionally, it would be good to implement pagination for this too, just in case
___
*[`src/utils/guests.ts` line 46 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn6949W-mW689Db4cDy:-Nn6949W-mW689Db4cDz:b4edgen) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L46)):*
> ```XML
>   const guestMembersInChannel = await app.client.conversations.members({
>     channel: channel,
>     limit: 500,
> ```

You should be able to bump up the limit to 900 for this function too


<!-- Sent from Reviewable.io -->

2024-01-02 22:29 UTC, wxp02 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60)* status: all files reviewed, 8 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/classes/SlackGuest.ts` line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn65YSY2CFPTUn9Wh9X:-Nn6Gy6R-hogPsDSweA7:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/classes/SlackGuest.ts#L4)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Could we generalize this into something like a `SlackUser` class? We can rename the `role` field into something like `userType` and use it to specify what kind of user they are, e.g. admin, owner, restricted (multi-channel guest), ultra_restricted (single-channel guest).

For `userType`, I would suggest that you use something like an enum to define them.
</blockquote></details>

Done.
___
*[`src/utils/guests.ts` line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn67XtNAObH4N90Nqil:-Nn7_2a_4VpiyFSRNTkO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L14)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

You should move out the `app.client.users.list` call and parsing the reponse into a list of `SlackUser`s into its own function under `src/utils/slack.ts`. Having it as its own function would make it easier to stub it out for unit testing purposes. 

Also note that this function fetches both active and deactivated users. We can definitely ignore deactivated users so your function could probably filter them out.
</blockquote></details>

Done.
___
*[`src/utils/guests.ts` line 15 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn66jMG7XMfcixZsOq5:-Nn7_6UI1dLrgLGoOCzd:b-qvqn8k) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L15)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

After some testing on the old minerva, we found out that the limit can be as high as 1000, so we could change this to something like 900 to ensure that we don't need to do pagination unless absolutely needed? Even now, there are 315 active accounts on the slack.
</blockquote></details>

I think is a good idea to omit pagination for now and keep the code succinct since we only have < 400 active accounts.
___
*[`src/utils/guests.ts` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn61uT_AprorXiO4Dih:-Nn7_th_0Pj0NxR-yG7q:btn5jp1) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L22)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Sorry, I didn't recall what Slack actually called this. By role, I mean user type as per my previous comment.
</blockquote></details>

Gotcha
___
*[`src/utils/guests.ts` line 36 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68hCmDtpjI_on_xCX:-Nn7g_En4LIctloC23XT:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L36)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

This JSDoc seems to be missing some parameters e.g. `channel`
</blockquote></details>

Done.
___
*[`src/utils/guests.ts` line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68Ha721VrznSaaAIf:-NnBGYwt2R0BWzh18zC6:b-ke7fdd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L41)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

It would be preferable to pass in a `SlackChannel` instead. Additionally, it would be good to either make it such that this function can be passed multiple channels to get all the single channel guests from or create a new getAllSingleChannelGuestsInChannel**s** function to do that
</blockquote></details>

Made some changes to this and created a new getAllSingleChannelGuestsInChannels function. Just curious why is it preferable to pass in a `SlackChannel` instead. IMO it's easier for users to just type in the name of the channel instead of having to figure out the `SlackChannel` of the desired channel.

I'll keep this as channel: string for now
___
*[`src/utils/guests.ts` line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68w-O3ShzPJwRBuFx:-NnB9Ogn0yCJPP-6okPb:bbfgnu) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L44)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

You should move this into its own function, similar to my suggestion for `app.client.users.list`. Additionally, it would be good to implement pagination for this too, just in case
</blockquote></details>

Done. Just like for the `app.client.users.list`, I'll omit pagination for now.
___
*[`src/utils/guests.ts` line 46 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn6949W-mW689Db4cDy:-Nn7gmgDBTgom6dkSXBk:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L46)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

You should be able to bump up the limit to 900 for this function too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-02 23:27 UTC, Darth-Raazi reviewed
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/classes/SlackUser.ts` line 6 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnBTzJ4DBzxh764F48M:-NnBTzJ4DBzxh764F48N:bd0kmo5) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/cdb41434a2eac30c671e7b27fcce18b14390ca48/src/classes/SlackUser.ts#L6)):*
> ```XML
> export enum UserType {
>   ADMIN = "admin",
>   OWNER = "owner",
> ```

What's the default or regular user type (i.e. slack full member)? I don't think everyone should be `OWNER` or `ADMIN`


<!-- Sent from Reviewable.io -->

2024-01-03 15:08 UTC, QuantumManiac requested changes
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60)* status: all files reviewed, 13 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/classes/SlackUser.ts` line 6 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnBTzJ4DBzxh764F48M:-NnEm3ed-JywFs1yoJCX:b9bxa3k) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/cdb41434a2eac30c671e7b27fcce18b14390ca48/src/classes/SlackUser.ts#L6)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

What's the default or regular user type (i.e. slack full member)? I don't think everyone should be `OWNER` or `ADMIN`
</blockquote></details>

+1 - There should be some full member enum for everyone who isn't any of these. See this: https://slack.com/help/articles/360018112273-Types-of-roles-in-Slack
___
*[`src/utils/users.ts` line 23 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnEmWqd3x7C5lUaESEi:-NnEmWqd3x7C5lUaESEj:b-k7rui9) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/cdb41434a2eac30c671e7b27fcce18b14390ca48/src/utils/users.ts#L23)):*
> ```XML
>     return UserType.ULTRA_RESTRICTED;
>   } else {
>     return UserType.RESTRICTED;
> ```

else should be the aforementioned full member enum I presume
___
*[`src/utils/users.ts` line 34 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnEqBpM3W_3w7Y-88-O:-NnEqBpM3W_3w7Y-88-P:bmx36p0) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/cdb41434a2eac30c671e7b27fcce18b14390ca48/src/utils/users.ts#L34)):*
> ```XML
> export async function allSlackUsers(app: App): Promise<SlackUser[]> {
>   const activeUsers: SlackUser[] = [];
>   const users = await app.client.users.list({
> ```

Could we move this function call out into`utils/slack.ts`, considering that it directly interacts with the slack API? Also, it would be good to add a parameter (probably defaulting as true) to specify whether or not to ignore deleted and deactivated members, just in case we do need them at some point, and generalize the function a bit more (e.g. `activeUsers` is just `users`).  
___
*[`src/utils/users.ts` line 55 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnEqyKi9gZ9MFkAqSpc:-NnEqyKi9gZ9MFkAqSpd:b-10g8f) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/cdb41434a2eac30c671e7b27fcce18b14390ca48/src/utils/users.ts#L55)):*
> ```XML
>  * @returns A promise that resolves to an array of SlackGuests of single channel guests.
>  */
> export async function getAllSingleChannelGuests(app: App, slackUsers: SlackUser[]): Promise<SlackUser[]> {
> ```

Given that single-channel guests don't exist in the development slack, can we have a check such that if the application is in development `environment.environment == "development"` we check for users of type ADMIN instead? It worked well enough for testing purposes in old minerva
___
*[`src/utils/users.ts` line 76 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnEpCJU13wWVPMmdLWt:-NnEpCJU13wWVPMmdLWu:bffrzi4) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/cdb41434a2eac30c671e7b27fcce18b14390ca48/src/utils/users.ts#L76)):*
> ```XML
>     throw new Error(`Channel ${channel} not found.`);
>   }
>   const allUsersInChannel = await app.client.conversations.members({
> ```

Could we move this function call out into its own independent function (e.g. `getChannelMembers`)  over in `utils/slack.ts`? 

Also, I see that we're just returning a list of user ID strings for this. Ideally, we would want to return a list of `SlackUsers` but I understand that it would be difficult to do given that this API response only returns the user IDs. 

How do you think we should deal with this? Maybe we could make a custom `SlackUserID` string type and use that instead? It's not too great but at the very least it would be helpful in type hinting.
___
*[`src/utils/guests.ts` line 15 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn66jMG7XMfcixZsOq5:-NnEmqRu1zZP8srsYEEn:b-oxuhpq) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L15)):*
<details><summary><i>Previously, wxp02 (Wenxu Poh) wrote…</i></summary><blockquote>

I think is a good idea to omit pagination for now and keep the code succinct since we only have < 400 active accounts.
</blockquote></details>

We have actually encountered issues where we weren't getting all the users due to the limit being too low, which necessitated pagination. Do note that users.list doesn't just return all active users, but also deleted/deactivated users, of which there are >1000. Because of this, it would be good to implement pagination anyway.
___
*[`src/utils/guests.ts` line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68Ha721VrznSaaAIf:-NnEnSCbA4pMBaa6CK8h:b7sj2b0) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L41)):*
<details><summary><i>Previously, wxp02 (Wenxu Poh) wrote…</i></summary><blockquote>

Made some changes to this and created a new getAllSingleChannelGuestsInChannels function. Just curious why is it preferable to pass in a `SlackChannel` instead. IMO it's easier for users to just type in the name of the channel instead of having to figure out the `SlackChannel` of the desired channel.

I'll keep this as channel: string for now
</blockquote></details>

So, we do want users to just type in the name of the channel but the Slack API functions usually require the channel ID and not the name. Because of this, we usually want to use the `SlackChannel` classes, which essentially act as a map between the channel name and its ID. 

Using `getAllSlackChannels` to get a list of all the slack channels in the workspace as `SlackChannel` objects and then using `filterSlackChannelFromName` to filter those channels into channel(s) with the name that you specify is easy enough, plus it handles the case where you want to get all the users in the default channels
___
*[`src/utils/guests.ts` line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68w-O3ShzPJwRBuFx:-NnEoUU640j9pH1IxfhG:ba9440n) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L44)):*
<details><summary><i>Previously, wxp02 (Wenxu Poh) wrote…</i></summary><blockquote>

Done. Just like for the `app.client.users.list`, I'll omit pagination for now.
</blockquote></details>

See previous comment about pagination. I do admit that you probably won't expect >900 users in a single channel but it would be nice to not have to potentially deal with in the future.


<!-- Sent from Reviewable.io -->

2024-01-04 22:41 UTC, wxp02 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/classes/SlackUser.ts` line 6 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnBTzJ4DBzxh764F48M:-NnHeehH3UUkJgVt4gcL:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/ddbac44d2729216bf2c21a0b4baa0c7f436d28ff/src/classes/SlackUser.ts#L6)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

+1 - There should be some full member enum for everyone who isn't any of these. See this: https://slack.com/help/articles/360018112273-Types-of-roles-in-Slack
</blockquote></details>

Done.
___
*[`src/utils/users.ts` line 23 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnEmWqd3x7C5lUaESEi:-NnHel1j55WUGRnXJXu0:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/ddbac44d2729216bf2c21a0b4baa0c7f436d28ff/src/utils/users.ts#L23)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

else should be the aforementioned full member enum I presume
</blockquote></details>

Done.
___
*[`src/utils/users.ts` line 34 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnEqBpM3W_3w7Y-88-O:-NnHo64W4B0VV5WJwD-Z:be047u1) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/ddbac44d2729216bf2c21a0b4baa0c7f436d28ff/src/utils/users.ts#L34)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Could we move this function call out into`utils/slack.ts`, considering that it directly interacts with the slack API? Also, it would be good to add a parameter (probably defaulting as true) to specify whether or not to ignore deleted and deactivated members, just in case we do need them at some point, and generalize the function a bit more (e.g. `activeUsers` is just `users`).
</blockquote></details>

Done. I set the parameter to false instead to align with the user.deleted logic
___
*[`src/utils/users.ts` line 55 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnEqyKi9gZ9MFkAqSpc:-NnLHDrv0yW4YZdulL4P:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/ddbac44d2729216bf2c21a0b4baa0c7f436d28ff/src/utils/users.ts#L55)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Given that single-channel guests don't exist in the development slack, can we have a check such that if the application is in development `environment.environment == "development"` we check for users of type ADMIN instead? It worked well enough for testing purposes in old minerva
</blockquote></details>

Done.
___
*[`src/utils/users.ts` line 76 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnEpCJU13wWVPMmdLWt:-NnLIxcT2yVrLMwoWL-K:bduxww7) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/ddbac44d2729216bf2c21a0b4baa0c7f436d28ff/src/utils/users.ts#L76)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Could we move this function call out into its own independent function (e.g. `getChannelMembers`)  over in `utils/slack.ts`? 

Also, I see that we're just returning a list of user ID strings for this. Ideally, we would want to return a list of `SlackUsers` but I understand that it would be difficult to do given that this API response only returns the user IDs. 

How do you think we should deal with this? Maybe we could make a custom `SlackUserID` string type and use that instead? It's not too great but at the very least it would be helpful in type hinting.
</blockquote></details>

I'm not sure if there's a viable way to return a list of SlackUsers, but I'll implement a custom `SlackUserID` string type for now. Fixed this.
___
*[`src/utils/guests.ts` line 15 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn66jMG7XMfcixZsOq5:-NnLWY080atHuMsDoxfX:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L15)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

We have actually encountered issues where we weren't getting all the users due to the limit being too low, which necessitated pagination. Do note that users.list doesn't just return all active users, but also deleted/deactivated users, of which there are >1000. Because of this, it would be good to implement pagination anyway.
</blockquote></details>

Done.
___
*[`src/utils/guests.ts` line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68Ha721VrznSaaAIf:-NnLbCc2-Q8SyvqSBTy0:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L41)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

So, we do want users to just type in the name of the channel but the Slack API functions usually require the channel ID and not the name. Because of this, we usually want to use the `SlackChannel` classes, which essentially act as a map between the channel name and its ID. 

Using `getAllSlackChannels` to get a list of all the slack channels in the workspace as `SlackChannel` objects and then using `filterSlackChannelFromName` to filter those channels into channel(s) with the name that you specify is easy enough, plus it handles the case where you want to get all the users in the default channels
</blockquote></details>

Done.
___
*[`src/utils/guests.ts` line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-Nn68w-O3ShzPJwRBuFx:-NnLX-hpERBjfPGcJEYw:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/019c80f33472c085a2338edb748d521c0eb20752/src/utils/guests.ts#L44)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

See previous comment about pagination. I do admit that you probably won't expect >900 users in a single channel but it would be nice to not have to potentially deal with in the future.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-04 23:02 UTC, QuantumManiac reviewed
LGTM! You should be good to finish up the final task in the issue.

I left a few review comments, but they're just nitpicks.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-:-NnLhVXl81es-M55z5Nq:b-duvayz)* status: all files reviewed, 4 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/utils/slack.ts` line 2 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnLfQZVAKDAHTIIxjJr:-NnLfQZVAKDAHTIIxjJs:b-rwissx) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/db3a2860ce7c9623a73531529ff8b09475f58f5b/src/utils/slack.ts#L2)):*
> ```XML
> import { App } from "@slack/bolt";
> import SlackUser, { UserType } from "../classes/SlackUser";
> ```

This is an interesting way of doing these imports!
___
*[`src/utils/slack.ts` line 32 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnLfbN50B9DzNaTt60W:-NnLfbN50B9DzNaTt60X:b-bv3f4b) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/db3a2860ce7c9623a73531529ff8b09475f58f5b/src/utils/slack.ts#L32)):*
> ```XML
>  * @returns A promise that resolves to an array of active SlackUser instances.
>  */
> export async function allSlackUsers(app: App, deactivatedMembers: boolean = false): Promise<SlackUser[]> {
> ```

nit: 
- rename function to `getAllSlackUsers`
- rename `deactivatedMembers` to `includeDeactivatedMembers`
___
*[`src/utils/users.ts` line 44 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnLgtMJAuBih1PgB58G:-NnLgtMJAuBih1PgB58H:b-1m5o14) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/db3a2860ce7c9623a73531529ff8b09475f58f5b/src/utils/users.ts#L44)):*
> ```XML
>   if (environment.environment == "development") {
>     allSingleChannelGuests = allActiveSlackUsers.filter((user) => {
>       return user.userType == "admin";
> ```

Could you leave a comment here about why we're filtering by "admin" in the development environment?

Something like "since the development Slack is on a free plan, multi- and single-channel guests dont' exist there. Therefore, we're validating functionality with admin users instead."


<!-- Sent from Reviewable.io -->

2024-01-05 04:57 UTC, wxp02 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/utils/users.ts` line 44 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnLgtMJAuBih1PgB58G:-NnMnmWi85Ns8DyztBOF:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/db3a2860ce7c9623a73531529ff8b09475f58f5b/src/utils/users.ts#L44)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Could you leave a comment here about why we're filtering by "admin" in the development environment?

Something like "since the development Slack is on a free plan, multi- and single-channel guests dont' exist there. Therefore, we're validating functionality with admin users instead."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-05 04:57 UTC, wxp02 commented
*[`src/utils/slack.ts` line 32 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnLfbN50B9DzNaTt60W:-NnMyzadDweXCmb2ahb6:b-886gsx) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/db3a2860ce7c9623a73531529ff8b09475f58f5b/src/utils/slack.ts#L32)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

nit: 
- rename function to `getAllSlackUsers`
- rename `deactivatedMembers` to `includeDeactivatedMembers`
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2024-01-05 13:46 UTC, QuantumManiac requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60)* status: all files reviewed, 3 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/utils/slack.ts` line 32 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnOpPW0CaIXBdHT6QHN:-NnOpPW1-KjPW84Mk0zh:b9jii66) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/62fda93e9b3696c2cb868bb60638e53ca2211fdd/src/utils/slack.ts#L32)):*
> ```XML
>  * @param text The text of the message to post
>  */
> export async function postMessageToSingleChannelGuestsInChannel(app: App, channel: SlackChannel): Promise<void> {
> ```

It would be good to separate out the Slack API logic (`app.client.chat.postMessage`) into its own function and then have this function call it. Also, remember to add a `text` parameter to this function before you merge the PR
___
*[`src/utils/users.ts` line 97 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnOr4Ro9VVDMXamVjbb:-NnOr4Ro9VVDMXamVjbc:bopl6vc) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/62fda93e9b3696c2cb868bb60638e53ca2211fdd/src/utils/users.ts#L97)):*
> ```XML
> export async function getAllSingleChannelGuestsInChannels(app: App, channels: SlackChannel[]): Promise<SlackUser[]> {
>   const allSingleChannelGuestsInChannels: SlackUser[] = [];
>   let seenIds = new Set();
> ```

Is this set necessary? Couldn't you just make `allSingleChannelGuestsInChannels` a set instead?

Also, the `!seenIds.has(user.id)` is probably unnecessary. If you `add` to a set that already has the element then it will not be added again and both your code and that code is pretty equivalent performance-wise

Remember to give typing to the set that you initialize: `new Set<string>()` (or `new Set<SlackUser>()` if you're making the revision mentioned above)


<!-- Sent from Reviewable.io -->

2024-01-06 18:03 UTC, Darth-Raazi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r2, 2 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-:-NnUwTpH3qyb_vvxyM14:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)



<!-- Sent from Reviewable.io -->

2024-01-07 00:45 UTC, wxp02 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/utils/slack.ts` line 32 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnOpPW0CaIXBdHT6QHN:-NnVsxOJ5wcHv9mgn0Wh:b-896fix) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/62fda93e9b3696c2cb868bb60638e53ca2211fdd/src/utils/slack.ts#L32)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

It would be good to separate out the Slack API logic (`app.client.chat.postMessage`) into its own function and then have this function call it. Also, remember to add a `text` parameter to this function before you merge the PR
</blockquote></details>

Done.
___
*[`src/utils/users.ts` line 97 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnOr4Ro9VVDMXamVjbb:-NnWLUf87Gp4cfa2shCV:b-8sdoa8) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/62fda93e9b3696c2cb868bb60638e53ca2211fdd/src/utils/users.ts#L97)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Is this set necessary? Couldn't you just make `allSingleChannelGuestsInChannels` a set instead?

Also, the `!seenIds.has(user.id)` is probably unnecessary. If you `add` to a set that already has the element then it will not be added again and both your code and that code is pretty equivalent performance-wise

Remember to give typing to the set that you initialize: `new Set<string>()` (or `new Set<SlackUser>()` if you're making the revision mentioned above)
</blockquote></details>

I can't make `allSingleChannelGuestsInChannels` a set, since `Set` in TS treats different object instances as unique even if their properties are identical, you would need to base the uniqueness on a property value rather than the object itself. So in this case, I'm basing the uniqueness on `user.id`.  

Also I think I can't remove the `!seenIds.has(user.id)`, I tried removing this line but I get duplicates

![image.png](https://files.reviewableusercontent.io/images/reviewable/83505161/Chnh3p98CEyrg4moUhvDBnoQ/image.png)


<!-- Sent from Reviewable.io -->

2024-01-07 13:21 UTC, QuantumManiac approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-:-NnZ4THf85Vj8swS-vw5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/utils/users.ts` line 97 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnOr4Ro9VVDMXamVjbb:-NnZ3gui6fOjzDa4NwsZ:b3fz0di) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/62fda93e9b3696c2cb868bb60638e53ca2211fdd/src/utils/users.ts#L97)):*
<details><summary><i>Previously, wxp02 (Wenxu Poh) wrote…</i></summary><blockquote>

I can't make `allSingleChannelGuestsInChannels` a set, since `Set` in TS treats different object instances as unique even if their properties are identical, you would need to base the uniqueness on a property value rather than the object itself. So in this case, I'm basing the uniqueness on `user.id`.  

Also I think I can't remove the `!seenIds.has(user.id)`, I tried removing this line but I get duplicates

![image.png](https://files.reviewableusercontent.io/images/reviewable/83505161/Chnh3p98CEyrg4moUhvDBnoQ/image.png)
</blockquote></details>

Okay, makes sense! This is fine with me then. 

More of a side-note: would it be possible to add functionality to hte `SlackUser` class such that equality is determined just by its `id` field? Might be a good way to deal with the issue that you mentioned, but we probably don't really need to do that.


<!-- Sent from Reviewable.io -->

2024-01-07 17:59 UTC, wxp02 commented
*[`src/utils/users.ts` line 97 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60#-NnOr4Ro9VVDMXamVjbb:-Nn_3cr63UBGnj5cJiDq:bhmsymc) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/62fda93e9b3696c2cb868bb60638e53ca2211fdd/src/utils/users.ts#L97)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Okay, makes sense! This is fine with me then. 

More of a side-note: would it be possible to add functionality to hte `SlackUser` class such that equality is determined just by its `id` field? Might be a good way to deal with the issue that you mentioned, but we probably don't really need to do that.
</blockquote></details>

I think that's a good idea, I'll add it in for now


<!-- Sent from Reviewable.io -->

2024-01-08 15:27 UTC, wxp02 reviewed
> Reviewed 2 of 4 files at r2, 1 of 2 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/60)* status: all files reviewed, 1 unresolved discussion (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)



<!-- Sent from Reviewable.io -->

2024-01-08 15:30 UTC, merged